### PR TITLE
Improve core credits in readme

### PR DESCRIPTION
**Pull request by birdybro**
The current core credits only give credit to the repo and not the developer (@hrvach) by name, also added a link to the MiSTer FPGA platform for proper context. I used the word port instead as the vast majority of what makes the PDP1 tick is it's CPU anyways, and there is more than the CPU code in this repo. I really like the changes you made to the colors and the option to load colors externally, very cool idea. :)

### CODE REVIEW

**Comment by birdybro** [comment]
Additionally, there have been many recent updates by Hrvoje here if you'd like to sync up your port --> https://github.com/hrvach/fpg1

**Comment by hrvach** [comment]
Thank you for this initiative, @birdybro - very nice of you!

**Comment by birdybro** [comment]
Your core that you made is a very important contribution to the preservation of classic computers. Thanks for the work you've done Hrvoje.

**Comment by hrvach** [comment]
> Your core that you made is a very important contribution to the preservation of classic computers. Thanks for the work you've done Hrvoje.

Thanks for the kind words, it is both nice to see some interest in the core (a very beginner project for me) and for attributing credits. If only there was more time available, I have so many ideas... :)

**Comment by birdybro** [comment]
Documenting the proposed changes here in a screenshot as the force push eliminated the diff in the PR.

image

**Comment by spacemen3** [comment]
New PR incoming shortly for this.

**Pull request closed without merging**
